#!/bin/sh

set -ev

export TICKER_TAPE_DATA_DIRECTORY=$METRICS_DIR

# Assemble Java system properties
JAVA_OPTS=""
[ -n "${TICKER_TAPE_LOG4J_LEVEL}" ] && JAVA_OPTS="${JAVA_OPTS} -Dlog4j.logLevel=${TICKER_TAPE_LOG4J_LEVEL}"

# Run It!
exec su socrata -c "/usr/bin/java -jar $JAVA_OPTS $TICKER_TAPE_ARTIFACT"
